### ISSUE TITLE
C_PREFIX is not working with EMBED_H TYPE

### ISSUE THREAD

**Issue by peterbud** [Makman2/GCR_CMake#11]
There is a typo [here 
](https://github.com/Makman2/GCR_CMake/blob/master/macros/CompileGResources.cmake#L90)

which prevents using C_PREFIX for header generation:

Instead of `if (NOT "${CG_ARG_C_OREFIX}" STREQUAL "")` -> `if (NOT "${CG_ARG_C_PREFIX}" STREQUAL "")`

**Comment by Makman2** [comment]
3.3 is released with the fix ;)
