### ISSUE TITLE
How to set alias

### ISSUE THREAD

**Issue by Keyikedalube** [Makman2/GCR_CMake#15]
I'm implementing an icon theme using `Gtk::IconTheme` for my gtkmm project

Since I'm adding resource path for my icon theme, the gresource xml file tags require setting `alias` attribute for all my icon files like this:
```
...
<gresource prefix="/absolute/path/to/resource">
  <file alias="abc.svg">relative/path/to/abc.svg</file>
  <file alias="def.png">relative/path/to/def.png</file
</gresource>
...
```

I don't know how to set the alias property with GCR_CMake. Is there a way to set it using your cmake script?

**Comment by Keyikedalube** [comment]
_Closed this issue due to inactivity_

**Comment by Makman2** [comment]
Sorry for the late response, plenty of stuff to do and haven't recently checked GitHub.

However, aliases are not supported. That would require proper implementation (feel free to submit a patch, I currently don't have time to dive into this repo again).

**Comment by Keyikedalube** [comment]
I did my own glib-compile-resources CMake script from scratch so I closed this issue :)

**Comment by Makman2** [comment]
I see, too bad it didn't end up in a PR :smile: 

Still, your requested feature seems viable to implement, so keeping it open :+1:

**Comment by Makman2** [comment]
Or rather I create a proper issue with more details.

**Comment by Makman2** [comment]
Moved feature request to https://github.com/Makman2/GCR_CMake/issues/18.
