### ISSUE TITLE
usage unclear if a c-file is needed

### ISSUE THREAD

**Issue by peterus** [Makman2/GCR_CMake#9]
I know how to create the c-file:
>compile_gresources(RESOURCE_FILE
>                    CML_OUT
>                    TARGET resources.c
>                    TYPE EMBED_C
>                    RESOURCES ${RESOURCE_LIST}
>                    PREFIX "/net/carrotIndustries/horizon")

But i have no idea how i can compile the resources.c file now, when i add the c-file to my program like this:
>ADD_EXECUTABLE(myprogram ${_SOURCES} ${_HEADERS} resources.c)

it is reporting an error when calling cmake:

>Cannot find source file:
>resources.c

**Comment by Makman2** [comment]
`resources.c` will probably reside in your build directory, you may have to specify `${CMAKE_BINARY_DIR}/resources.c` or `${CMAKE_CURRENT_BINARY_DIR}/resources.c` instead and setting the property `GENERATED` on `resources.c` (See https://stackoverflow.com/questions/32512872/cmake-executable-with-auto-generated-sources) :smile:

**Comment by peterus** [comment]
thanks!
worked with:

> SET_SOURCE_FILES_PROPERTIES{${CMAKE_CURRENT_BINARY_DIR}/resources.c PROPERTIES GENERATED TRUE)

**Comment by Makman2** [comment]
I guess it's also working without `set_source_files_properties`, because GCR_CMake uses `add_custom_command` to create new files (and not plain targets).
